_target_: src.pipelines.foldseek.FoldseekGenerationsPipeline
evaluation_parquet: null
evaluation_accessions_file: null
parquet_index: null
pipeline_id: foldseek_n${.num_generations}
num_generations: 10
