gym_val_assay_list:
  - BLAT_ECOLX_Jacquier_2013
  - CALM1_HUMAN_Weile_2017
  - DYR_ECOLI_Thompson_2019
  - DLG4_RAT_McLaughlin_2012
  - REV_HV1H2_Fernandes_2016
  - TAT_HV1BR_Fernandes_2016
  - RL40A_YEAST_Roscoe_2013
  - P53_HUMAN_Giacomelli_2018_WT_Nutlin
  - UBR5_HUMAN_Tsuboyama_2023_1I2T
  - TRPC_SACS2_Chan_2017
  - TPOR_HUMAN_Bridgford_2020
  - SQSTM_MOUSE_Tsuboyama_2023_2RRU
  - RASK_HUMAN_Weng_2022_binding-DARPin_K55
  - PTEN_HUMAN_Mighell_2018
  - Q53Z42_HUMAN_McShan_2019_binding-TAPBPR
  - YAP1_HUMAN_Araya_2012
  - TADBP_HUMAN_Bolognesi_2019
  - RL40A_YEAST_Mavor_2016
  - RL20_AQUAE_Tsuboyama_2023_1GYZ
  - RASK_HUMAN_Weng_2022_abundance
  - RAD_ANTMA_Tsuboyama_2023_2CJJ
  - Q59976_STRSQ_Romero_2015
  - Q837P4_ENTFA_Meier_2023
  - A0A2Z5U3Z0_9INFA_Doud_2016
  - A0A192B1T2_9HIV1_Haddox_2018
