vocab_size: 68
gym_val_assay_list:
  - BLAT_ECOLX_Jacquier_2013
  - CALM1_HUMAN_Weile_2017
  - DYR_ECOLI_Thompson_2019
  - DLG4_RAT_McLaughlin_2012
  - REV_HV1H2_Fernandes_2016
  - TAT_HV1BR_Fernandes_2016
  - RL40A_YEAST_Roscoe_2013
  - P53_HUMAN_Giacomelli_2018_WT_Nutlin

sequence_features:
  - ds_name
  - identifier
  - input_ids
  - attention_mask
  - original_size
  - batch_size
