_target_: src.utils.trainer.ProFamTrainer

default_root_dir: ${paths.output_dir}

max_epochs: 5
max_steps: -1

accelerator: cpu
devices: 1

check_val_every_n_epoch: 1
val_check_interval: 1.0
target_tokens_per_batch: 500_000
tokens_per_document: 10_000
batch_size: ${data.batch_size}
# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

log_every_n_steps: 10  # number of gradient steps https://github.com/Lightning-AI/pytorch-lightning/issues/9726
timeout: null

profiler:
  name: null # supported profilers: null, simple, advanced, pytorch
  log_tensorboard: False
  simple:
    _target_: SimpleProfiler
  advance:
    _target_: AdvancedProfiler
    filename: advanced_perf_logs
    dirpath: "./profiler_logs"
  pytorch:
    _target_: PyTorchProfiler
    filename: pytorch_perf_logs
    dirpath: "./profiler_logs"
    # pytorch profiler kwargs
    record_shapes: True
    profile_memory: True
    with_stack: True
    with_flops: False
    with_modules: False
    acc_events: False
