defaults:
  - default

strategy: ddp
accelerator: gpu
devices: 2
num_nodes: 1
sync_batchnorm: True
timeout: 120

# mixed precision gives keeps model weights as 32bit floats but performs operations in 16bit where possible
precision: bf16-true  #  bf16-mixed, bf16-true, 16-mixed, 16-true, 32-true
