# @package _global_

defaults:
  - override /logger: wandb
  - override /trainer: gpu

data:
  num_workers: 5

trainer:
  precision: 16-mixed

logger:
  wandb:
    mode: "offline"

float32_matmul_precision: null
