# @package _global_

defaults:
  - override /logger: wandb
  - override /trainer: ddp

data:
  num_workers: 6  # per gpu

trainer:
  precision: 16-mixed
  devices: 6

logger:
  wandb:
    mode: "offline"

float32_matmul_precision: null
