_target_: src.utils.tokenizers.ProFamTokenizer
tokenizer_file: src/data/components/profam_tokenizer.json
unk_token: "[UNK]"
pad_token: "[PAD]"
bos_token: "[start-of-document]"
sep_token: "[SEP]"
mask_token: "?"
seq_struct_sep_token: "|"
add_final_sep: true
add_bos_token: true
add_document_token: true
mask_below_plddt: 80  # > 90 is 'very high' confidence in af browser
max_res_pos_in_seq: ${model.max_res_pos_in_seq}
