_target_: src.data.tokenizers.ProFamTokenizer
tokenizer_file: data/profam_tokenizer.json
unk_token: "[UNK]"
pad_token: "[PAD]"
bos_token: "[start-of-document]"
sep_token: "[SEP]"
mask_token: "?"
seq_struct_sep_token: "|"
add_final_sep: true
add_bos_token: true
add_document_token: true

