_target_: src.evaluators.esmfold.ESMFoldSamplingEvaluator
name: esmfold
half_precision: False
num_samples: null
save_structures: False
max_length: 512  # filter applied when running esmfold on generations to avoid oom
