_target_: src.evaluators.esmfold.ESMFoldSamplingEvaluator
device: "cuda:0"  # TODO: check this works in distributed.
seed: 52
name: esmfold
half_precision: False
num_samples: 100
save_structures: False
