_target_: src.data.processors.ProteinDocumentPreprocessor
# TODO: option for msa_pos
defaults:
  - cfg: raw
# https://github.com/facebookresearch/hydra/issues/1939
# https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/
# TODO: handle coords in this case
transform_fns:
  - _target_: src.data.processors.transforms.interleave_structure_sequence
    _partial_: true
    structure_first_prob: 1.0
  - _target_: src.data.processors.transforms.replace_nans_in_coords
    _partial_: true
    fill_value: 0.0
