_target_: src.data.preprocessing.ParquetStructureSequencePreprocessorConfig
keep_insertions: false
to_upper: false
keep_gaps: false
document_token: "[MSA]"
structure_tokens_col: "msta_3di"
is_aligned: false
truncate_after_n_sequences: null
use_msa_pos: true
interleave_structure_tokens: true
