_target_: src.data.preprocessing.ParquetStructurePreprocessor
defaults:
  - config: raw
  - transform_fns: rotate_and_noise
structure_tokens_col: null  # msta_3di
interleave_structure_sequence: true
infer_representative_from_identifier: true
# https://github.com/facebookresearch/hydra/issues/1939
# https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/
