_target_: src.data.preprocessing.ParquetSequencePreprocessorConfig
keep_insertions: false
to_upper: false
keep_gaps: true
document_token: "[MSA]"
max_tokens: ${globals.max_tokens}
shuffle: ${globals.shuffle}
truncate_after_n_sequences: null
use_msa_pos: false