_target_: src.data.processors.ProteinDocumentPreprocessor
defaults:
  - cfg: raw
transform_fns:
  - _target_: src.data.processors.transforms.replace_nans_in_coords
    _partial_: true
    fill_value: 0.0
  - _target_: src.data.processors.transforms.repeat_random_sequence_in_family
    _partial_: true
