# @package _global_

defaults:
  - /evaluator@evaluators.esmfold_if: esmfold_if
  - /evaluator@evaluators.sequence_recovery: sequence_recovery
  - override /sampler: neat-thunder_if
  - override /pipeline: cath43

evaluators:
  sequence_recovery:
    verbose: true
  esmfold_if:
    save_structures: false
