_target_: src.models.gpt.GPT2LitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
lr: 1e-4
config:
  _target_: transformers.GPT2Config
  vocab_size: 66
  n_embd: 768
  n_head: 12
  n_layer: 12
  n_positions: 2048
use_seq_pos: ${data.use_seq_pos}  # embed sequence relative position
max_seq_pos: ${data.max_seq_pos}  # maximum sequence position
