_target_: src.models.gpt.GPT2SingleSequenceLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
config:
  _target_: transformers.GPT2Config
  vocab_size: 66
  n_embd: 384
  n_head: 4
  n_layer: 4
  n_positions: 2048
