_target_: src.models.gpt.GPT2SingleSequenceLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
optimizer: adamw
config:
  _target_: transformers.GPT2Config
  vocab_size: ${constants.vocab_size}
  n_embd: 384
  n_head: 4
  n_layer: 4
  n_positions: 2048
  attn_implementation: flash_attention_2  # eager/flash_attention_2/sdpa
embed_coords: false
embed_sequence_index: false
embed_residue_index: true
max_seq_pos_in_doc: 1024
