_target_: src.models.gpt.GPT2SingleSequenceLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
config:
  _target_: transformers.GPT2Config
  vocab_size: ${constants.vocab_size}
  n_embd: 768
  n_head: 12
  n_layer: 12
  n_positions: 2048
  attn_implementation: null  # eager/flash_attention_2/sdpa
embed_coords: false
embed_sequence_index: false
