_target_: src.models.gpt.GPT2SingleFamilyLitModule
scheduler_name: "constant_with_warmup"
num_warmup_steps: 200
config:
  _target_: transformers.GPT2Config
  vocab_size: 41
  n_embd: 256
  n_head: 4
  n_layer: 3
