_target_: src.models.llama.LlamaLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
lr: 1e-3
use_kv_cache_for_scoring: true
optimizer: adamw
pass_res_pos_in_doc_as_position_ids: true
config:
  _target_: transformers.LlamaConfig
  vocab_size: ${constants.vocab_size}
  hidden_size: 768
  intermediate_size: 3072
  num_attention_heads: 12
  num_hidden_layers: 6
  rope_theta: 500000
  max_position_embeddings: 32_768  # used in llama rope implementation
  scoring_max_tokens: 10240
  attn_implementation: flash_attention_2  # eager/flash_attention_2/sdpa
