_target_: src.models.llama.LlamaLitModule
scheduler_name: "constant_with_warmup"
num_warmup_steps: 1000
lr: 1e-3
use_kv_cache_for_scoring: true
pass_res_pos_in_doc_as_position_ids: true
optimizer: adamw
config:
  _target_: transformers.LlamaConfig
  vocab_size: ${constants.vocab_size}
  hidden_size: 1024
  intermediate_size: 4096
  num_attention_heads: 16
  num_hidden_layers: 12
  rope_theta: 500000  # n.b. llama uses 500,000
  max_position_embeddings: 32_768  # used in llama rope implementation
  scoring_max_tokens: 10240
  attn_implementation: flash_attention_2  # eager/flash_attention_2/sdpa
