# designed to be comparable in param count to IF models like MPNN
_target_: src.models.llama.LlamaLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
lr: 1e-3
use_kv_cache_for_scoring: true
pass_res_pos_in_doc_as_position_ids: true
optimizer: adamw
config:
  _target_: transformers.LlamaConfig
  vocab_size: ${constants.vocab_size}
  hidden_size: 128
  intermediate_size: 512
  num_attention_heads: 2
  num_hidden_layers: 5
  rope_theta: 500000
  max_position_embeddings: 8192  # used in llama rope implementation
  scoring_max_tokens: 10240
  attn_implementation: null  # eager/flash_attention_2/sdpa
