# TO BE USED FOR TEST CASES ONLY
_target_: src.models.llama.LlamaLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
lr: 1e-3
embed_coords: false
embed_sequence_index: false
embed_residue_index: true
max_seq_pos_in_doc: 1024
max_res_pos_in_seq: 4096
pass_res_pos_in_doc_as_position_ids: false
config:
  _target_: transformers.LlamaConfig
  vocab_size: ${constants.vocab_size}
  hidden_size: 64
  intermediate_size: 128
  num_attention_heads: 4
  num_hidden_layers: 1
  rope_theta: 500000
  max_position_embeddings: 2048  # used in llama rope implementation
  scoring_max_tokens: 10240
  attn_implementation: null
