_target_: src.models.mistral_lit_module.MistralLitModule
config:
  _target_: transformers.MistralConfig
  vocab_size: ${constants.vocab_size}
  hidden_size: 128
  intermediate_size: 512
  num_hidden_layers: 3
  num_attention_heads: 4
  num_key_value_heads: 4
  pad_token_id: 25
  bos_token_id: 26
  eos_token_id: 27
  sliding_window: 4096
  attn_implementation: null  # eager/flash_attention_2/sdpa

scoring_max_tokens: 8000  # number of tokens to use per batch when scoring mutants
use_kv_cache_for_scoring: True  # use key-value cache for scoring
embed_coords: false
embed_sequence_index: false
