_target_: src.models.mistral_lit_module.MistralLitModule
scheduler_name: "inverse_sqrt"
num_warmup_steps: 1000
lr: 1e-4
config:
  _target_: transformers.MistralConfig
  vocab_size: 41
  hidden_size: 512
  intermediate_size: 2048
  num_attention_heads: 4
  num_key_value_heads: 4
  num_hidden_layers: 6
  sliding_window: 1024

scoring_max_tokens: 8000
use_kv_cache_for_scoring: True
use_seq_pos: ${data.use_seq_pos}
max_seq_pos: ${data.max_seq_pos}