_target_: src.models.inference.ProFamSampler
defaults:
  - model: llama_small
  - /preprocessor@prompt_build.preprocessor: parquet_3di_with_interleaved_coords
name: northern-plant  # suggestion: use wandb run name
checkpoint_path: outputs/inverse_folding/batched_preprocess/2024-09-15_12-28-15/checkpoints/last.ckpt
sampling_kwargs:
  batch_size: 3
  max_length: 512
prompt_builder:
  _target_: src.models.inference.InterleavedInverseFoldingPromptBuilder
  preprocessor:
    structure_tokens_col: null
    config:
      document_token: "[AFDB]"
  max_tokens: 1536
  seed: 42
  representative_only: true

# alternative model loading
# model:
#   _target_: src.models.base.load_checkpoint
#   checkpoint_dir: outputs/pfam_train_seqpos
