"""
This script generates random sythetic MSAs for the CASP16 targets.
It takes the .a3m files which are the synthetic MSAs generated by ProFam
and for each position that is not a gap, it selects either the query AA
in that position or a random AA: the probability of selecting the query AA
is whatever the seq-id is for that particular row.
"""
import glob
import os
import random
import re

def generate_random_synthetic_MSAs(input_file, output_file):
    """Generate a randomized synthetic MSA based on per-row seq identity.

    Rules:
    - Treat the first sequence as the query.
    - Compute per-row sequence identity to the query over aligned columns
      (A3M uppercase letters and '-' after removing lowercase inserts), using
      positions where both query and row have a residue (non-gap) as the
      denominator.
    - For each aligned, non-gap residue in the row, select either:
        * the query residue with probability = seq_identity(row, query)
        * a random amino acid with probability = 1 - seq_identity
          (excluding the query residue to keep the exact probability)
    - Preserve gaps ('-') and lowercase insertions exactly as in the input.
    """

    aa_alphabet = "ACDEFGHIKLMNPQRSTVWY"

    def remove_inserts(seq: str) -> str:
        return re.sub(r"[a-z]", "", seq)

    def parse_a3m(path: str):
        headers = []
        seqs = []
        current_header = None
        current_seq_parts = []
        with open(path, "r") as f:
            for line in f:
                line = line.rstrip("\n")
                if not line:
                    continue
                if line.startswith(">"):
                    if current_header is not None:
                        seqs.append("".join(current_seq_parts))
                        current_seq_parts = []
                    current_header = line
                    headers.append(current_header)
                else:
                    current_seq_parts.append(line.strip())
            if current_header is not None:
                seqs.append("".join(current_seq_parts))
        return list(zip(headers, seqs))

    def write_a3m(records, path: str):
        with open(path, "w") as f:
            for header, seq in records:
                f.write(f"{header}\n")
                f.write(f"{seq}\n")

    records = parse_a3m(input_file)
    if not records:
        raise ValueError(f"No sequences found in A3M: {input_file}")

    query_header, query_seq = records[0]
    query_aligned = remove_inserts(query_seq)

    def compute_seq_identity(row_aligned: str, query_aligned: str) -> float:
        if len(row_aligned) != len(query_aligned):
            raise ValueError(
                "Aligned sequences differ in length after removing inserts: "
                f"{len(row_aligned)} vs {len(query_aligned)} in {input_file}"
            )
        matches = 0
        denom = 0
        for rc, qc in zip(row_aligned, query_aligned):
            rc_is_res = rc.isalpha()
            qc_is_res = qc.isalpha()
            if rc_is_res and qc_is_res:
                denom += 1
                if rc == qc:
                    matches += 1
        return (matches / denom) if denom > 0 else 0.0

    def sample_random_residue(exclude: str | None) -> str:
        if exclude is not None and exclude in aa_alphabet:
            choices = [a for a in aa_alphabet if a != exclude]
        else:
            choices = list(aa_alphabet)
        return random.choice(choices)

    out_records = []
    out_records.append((query_header, query_seq))

    for header, seq in records[1:]:
        row_aligned = remove_inserts(seq)
        p_keep_query = compute_seq_identity(row_aligned, query_aligned)

        # Build mutated aligned (uppercase/'-' only) sequence
        mutated_aligned_chars = []
        for rc, qc in zip(row_aligned, query_aligned):
            if rc == '-':
                mutated_aligned_chars.append('-')
                continue
            if rc.isalpha():
                if not qc.isalpha():
                    # Query has a gap here; pick a random residue
                    mutated_aligned_chars.append(sample_random_residue(None))
                else:
                    if random.random() < p_keep_query:
                        mutated_aligned_chars.append(qc)
                    else:
                        mutated_aligned_chars.append(sample_random_residue(qc))
            else:
                # Unexpected symbol, keep as-is
                mutated_aligned_chars.append(rc)

        # Re-insert lowercase inserts exactly as they appeared in the original row
        mutated_aligned_iter = iter(mutated_aligned_chars)
        rebuilt_chars = []
        for ch in seq:
            if ch.islower():
                rebuilt_chars.append(ch)
            else:
                rebuilt_chars.append(next(mutated_aligned_iter))
        mutated_seq = "".join(rebuilt_chars)

        out_records.append((header, mutated_seq))

    os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
    write_a3m(out_records, output_file)

if __name__=="__main__":
    input_pattern = "../CASP16/ProFam_synthetic_msas/*.a3m"
    output_dir = "../CASP16/random_synthetic_msas"
    input_files = glob.glob(input_pattern)
    os.makedirs(output_dir, exist_ok=True)
    for input_file in input_files:
        output_file = os.path.join(output_dir, os.path.basename(input_file))
        if os.path.exists(output_file):
            print(f"Skipping {input_file} as output file already exists")
            continue
        generate_random_synthetic_MSAs(input_file, output_file)