# @package _global_

# TODO: decide whether we do want pretrained_model to be separately configurable
defaults:
  - _self_
  - sampler: null  # needs to be set
  - pipeline: pfam_example
  - evaluator: pfam_profile_hmm
  - paths: benchmark  # TODO: handle hydra path?
  - extras: default
  - constants: profam

rerun_sampler: false
rerun_evaluator: false
