# @package _global_

# TODO: decide whether we do want pretrained_model to be separately configurable
defaults:
  - _self_
  - sampler: null  # needs to be set
  - pipeline: pfam_example
  - evaluator: pfam_profile_hmm
  - extras: default
  - tokenizer: profam

rerun_model: false
rerun_evaluator: false
task_name: "eval"
