# N.B. this model requires COORDS TO BE DUPLICATED ON THE SEQUENCE SIDE
# A llama small model trained on foldseek representatives
_target_: src.models.scoring.ProFamScorer
defaults:
  - /model: llama_medium
  - /tokenizer@model.tokenizer: profam
  - /data/dataset/preprocessor@prompt_builder.preprocessor: parquet_structure
name: twilight-snowflake  # suggestion: use wandb run name
checkpoint_path: outputs/inverse_folding/twilight-snowflake/checkpoints/last.ckpt
prompt_builder:
  _target_: src.models.inference.InterleavedInverseFoldingPromptBuilder
  preprocessor:
    structure_tokens_col: null
    config:
      document_token: "[AFDB]"
  max_tokens: 1536
  seed: 42
model:
  scoring_max_tokens: 10240  # determines batch size - rather than document size
  embed_coords: True
  tokenizer:
    max_tokens: 1536

# alternative model loading
# model:
#   _target_: src.models.base.load_checkpoint
#   checkpoint_dir: outputs/pfam_train_seqpos
