- _target_: src.data.processors.transforms.apply_plddt_mask
  _partial_: true
  threshold: 80.0  # TODO: make this easier to configure
# n.b. if we train on unnoised and evaluate on noised, it's a total disaster
# - _target_: src.data.processors.transforms.noise_backbones
#   _partial_: true
#   std: 0.1
- _target_: src.data.processors.transforms.centre_backbones
  _partial_: true
  scale: 6.0
- _target_: src.data.processors.transforms.rescale_backbones
  _partial_: true
- _target_: src.data.processors.transforms.replace_nans_in_coords
  _partial_: true
  fill_value: 0.0
