_target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
defaults:
  - /pipeline: cath43
  - /evaluator@evaluators.esmfold_if: esmfold_if
  - /evaluator@evaluators.recovery: sequence_recovery
  - /prompt_builder: interleaved_inverse_folding  # must be set
  - /preprocessor@prompt_builder.preprocessor: null  # must be set
prompt_builder:
  max_tokens: ${data.max_tokens}
  seed: 42
sampling_kwargs:
  batch_size: 48
  temperature: 0.3
pipeline:
  split_name: validation
  num_generations: 1
  save_results_to_file: false
match_representative_length: true
