_target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
defaults:
  - /pipeline: foldseek
  - /evaluator: esmfold
evaluator:
  num_samples: null
sampling_kwargs:
  batch_size: 3
pipeline:
  num_generations: 3
  save_to_file: false
  evaluation_parquet: null
  evaluation_accessions_file: null
