_target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
defaults:
  - /pipeline: foldseek
  - /evaluator: esmfold
  - /prompt_builder: default
  - /preprocessor@prompt_builder.preprocessor: null  # must be set
prompt_builder:
  max_tokens: ${data.max_tokens}
  seed: 42
evaluator:
  num_samples: null
sampling_kwargs:
  batch_size: 3
pipeline:
  num_generations: 3
  save_to_file: false
  evaluation_parquet: null
  evaluation_accessions_file: null
  max_instances: 50
