_target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
defaults:
  - /pipeline: pfam
  - /evaluator: pfam_profile_hmm
evaluator:
  num_samples: null
sampling_kwargs:
  batch_size: 3
pipeline:
  num_generations: 9
  save_to_file: false
seed: 42  # for prompt builder
