# callback for family conditioned sampling with ESMFold evaluation
_target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
defaults:
  - /preprocessor@prompt_builder.preprocessor: raw_from_msa_add_final_sep
pipeline:
  _target_: src.pipelines.family_sequence.FamilySequenceEvaluationPipeline
  parquet_path: "../data/funfams/s100_noali_parquets/train_val_test_split/val/val_000.parquet"
  num_generations: 3
  max_tokens: 20000
  max_generated_length: 90
  pipeline_id: funfam_val
  save_results_to_file: false
evaluators:
  _target_: src.evaluators.esmfold.ESMFoldSamplingEvaluator
  name: esmfold_example
prompt_builder:
  _target_: src.models.inference.PromptBuilder
