sampling_eval_callback:
  _target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
  pipeline:
    _target_: src.pipelines.funfam.FunfamEvaluationPipeline
    num_generations: 3
    max_tokens: 30000
    max_generated_length: 90
    pipeline_id: funfam_val
    save_results_to_file: false
  evaluators:
    _target_: src.evaluators.esmfold.ESMFoldSamplingEvaluator
    name: esmfold_example
  prompt_builder:
    _target_: src.models.inference.PromptBuilder
    preprocessor: null
