
  # We are going to instantiate a SamplingEvaluationPipelineCallback.
  # this will be called on epoch end to evaluate sampled sequences from
  # the model that is being trained.
  # It is instantiated with a pipeline, evaluators, prompt_builder
  # prompt builder in instantiated with a preprocessor, it is called
  # by passing in a protein document and a tokenizer and it returns
  # a protein document.

  # SamplingEvaluationPipelineCallback has on_validation_epoch_end
  # method which takes trainer and model.
  # it instantiates a a ProFamSampler with the model, prompt_builder,
  # sampling_kwargs, and match_representative_length.
  # it then runs the pipeline with the sampler and evaluators.
  # the results are returned as a list of dataframes.
  # it calls pipeline.run with the sampler, self.Evaluators and
  # it gets a list of results_dfs from each evaluator. logs the
  # results.

  # GenerationsEvaluatorPipeline has a run method that takes sampler,
  # evaluators this does the following:

  # - self.load_protein_document(instance_id)
  # - sampler.sample_seqs(protein_document, self.num_generations)
  # - iterate over each evaluator, for each:
  #   - self.run_evaluator_on_instance:
  #     - retrieve generations based on instance_id and sampler_name
  #     - metrics = evaluator.evaluate_samples(
  #       prompt=prompt,
  #       protein_document=protein_document,
  #       samples=generated_sequences,
  #       output_dir=output_dir,
  #       device=device,
  #     )
  # results from each evaluator are saved in self.results_dfs
  # ESMFoldSamplingEvaluator has a run method that takes a sa
sampling_eval_callback:
  _target_: src.pipelines.callback.SamplingEvaluationPipelineCallback
  pipeline:
    _target_: src.pipelines.funfam.FunfamEvaluationPipeline
    num_generations: 3
    max_tokens: 30000
    max_generated_length: 90
    pipeline_id: funfam_val
    save_results_to_file: false
  evaluators:
    _target_: src.evaluators.esmfold.ESMFoldSamplingEvaluator
    name: esmfold_example
  prompt_builder:
    _target_: src.models.inference.PromptBuilder
    preprocessor: null
